name: backend

on:
  push:
    paths:
      - backend/**

jobs:
  build-and-clang-tidy:
    runs-on: ubuntu-latest
    container: ghcr.io/iraspa/ubuntu-22-llvm-18:latest
    steps:
      - name: Setup clang-tidy
        run: apt install -y clang-tidy

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v2

      - name: Checkout project
        uses: actions/checkout@v4
        with:
          source-path: backend/source/

      - name: Build project and run clang-tidy
        uses: threeal/cmake-action@v2
        with:
          source-path: backend/source/

  clang-format:
    runs-on: ubuntu-latest
    container: ghcr.io/iraspa/ubuntu-22-llvm-18:latest
    steps:
      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v2

      - name: Checkout project
        uses: actions/checkout@v4
        with:
          source-path: backend/source

      - name: Run clang-format only
        uses: threeal/cmake-action@v2
        with:
          source-path: backend/source/
          build-args: |
            --target clang-format
