name: frontend

on:
  push:
    paths:
      - frontend/**

jobs:
  prettier:
    runs-on: ubuntu-latest
    container: ghcr.io/iraspa/ubuntu-22-llvm-18:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          working_directory: frontend/source/
