name: frontend

on:
  push:
    paths:
      - frontend/**

jobs:
  prettier:
    runs-on: ubuntu-latest
    container: ghcr.io/iraspa/ubuntu-22-llvm-18:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          source-dir: frontend/source/
