name: frontend

on:
  push:
    paths:
      - frontend/**

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: |
          yarn
          yarn prettier frontend/source/ --check
      - uses: autofix-ci/action@v1
